# 인공지능수학 Lecture1/Lab1 — Solution



In [1]:
import numpy as np
import matplotlib.pyplot as plt

---
# Part A. Lecture 1 익히기 활동 정답

## 활동 1. 인덱싱

In [2]:
A = np.array([[ 1,  2,  3,  4],
              [ 5,  6,  7,  8],
              [ 9, 10, 11, 12],
              [13, 14, 15, 16]])
B = np.array([[10, 60], [30, 80], [50, 20]])

print("(1)", A[1, 2])          # 7
print("(2)", A[-1])            # [13 14 15 16]
print("(3)\n", A[1:3, 1:3])   # [[6 7][10 11]]
print("(4)", B[B > 50])        # [60 80]

(1) 7
(2) [13 14 15 16]
(3)
 [[ 6  7]
 [10 11]]
(4) [60 80]


## 활동 2. 1D vs 2D

In [3]:
v = np.array([1, 2, 3])

# (1) 열벡터 만들기
v_col_1 = v.reshape(-1, 1)       # (3,1)
v_col_2 = v[:, np.newaxis]       # (3,1)
print("(1)", v_col_1.shape, v_col_2.shape)

# (2) shape 확인
W = np.ones((4, 3))
print("(2a) W @ v       shape:", (W @ v).shape)        # (4,)  ← 1D 결과
print("(2b) W @ v_col_1 shape:", (W @ v_col_1).shape)  # (4,1) ← 2D 결과

# (3) 전치 비교
print("(3) v.T shape:", v.T.shape,          # (3,) 변화 없음!
      "  v_col_1.T shape:", v_col_1.T.shape) # (1,3)

(1) (3, 1) (3, 1)
(2a) W @ v       shape: (4,)
(2b) W @ v_col_1 shape: (4, 1)
(3) v.T shape: (3,)   v_col_1.T shape: (1, 3)


## 활동 3. 🐛 버그 분석

**버그 1:** `axis=1` → 행별 평균 (shape `(3,)`) 을 구함. 표준화는 열별 평균이 필요하므로 `axis=0` 이어야 함.

**버그 2:** `X_norm.shape()` → `shape`은 속성(attribute)이지 메서드가 아님. 괄호 제거 필요.


In [ ]:
X = np.array([[84.0, 10.0], [59.0, 5.0], [112.0, 20.0]])

mean   = X.mean(axis=0)   # Fix 1: axis=0
std    = X.std(axis=0)
X_norm = (X - mean) / std

print("shape:", X_norm.shape)   # Fix 2: no parentheses
print("column means (≈ 0):", X_norm.mean(axis=0).round(10))
print("column stds  (≈ 1):", X_norm.std(axis=0).round(10))

shape: (3, 2)
column means (≈ 0): [0. 0.]
column stds  (≈ 1): [1. 1.]


---
# Part B. Lab 1 손문제 풀이

## 문제 1. 벡터 연산

**(1)** $\mathbf{a} + \mathbf{b} = \begin{bmatrix} 6 \\ 1 \\ 2 \end{bmatrix}$

**(2)** $2\mathbf{a} - \mathbf{b} = \begin{bmatrix} 4 \\ -2 \\ 6 \end{bmatrix} - \begin{bmatrix} 4 \\ 2 \\ -1 \end{bmatrix} = \begin{bmatrix} 0 \\ -4 \\ 7 \end{bmatrix}$

**(3)** $\mathbf{a} \cdot \mathbf{b} = 2\times4 + (-1)\times2 + 3\times(-1) = 8 - 2 - 3 = 3$

**(4)** $\|\mathbf{a}\| = \sqrt{4+1+9} = \sqrt{14} \approx 3.742$

In [ ]:
a = np.array([2, -1, 3])
b = np.array([4,  2, -1])
print("(1)", a + b)                  # [6  1  2]
print("(2)", 2*a - b)                # [0 -4  7]
print("(3)", np.dot(a, b))           # 3
print("(4)", np.linalg.norm(a))      # 3.7416...

## 문제 2. 행렬 곱셈

**(1)**
$$AB = \begin{bmatrix}1\cdot4+0\cdot2 & 1\cdot1+0\cdot5 \\ 2\cdot4+3\cdot2 & 2\cdot1+3\cdot5\end{bmatrix} = \begin{bmatrix}4 & 1 \\ 14 & 17\end{bmatrix}$$

**(2)**

| 연산 | 가능? | 결과 shape |
|:---|:---:|:---:|
| $A_{3\times4} \cdot B_{4\times2}$ | O | $(3\times2)$ |
| $A_{2\times5} \cdot B_{5\times1}$ | O | $(2\times1)$ |
| $A_{3\times2} \cdot B_{3\times4}$ | X | — (앞 열 2 ≠ 뒤 행 3) |
| $A_{1\times6} \cdot B_{6\times1}$ | O | $(1\times1)$ |

## 문제 3. 1D vs 2D

**(1)**

| 코드 | shape | 설명 |
|---|---|---|
| `np.array([1,2,3])` | `(3,)` | 1D 배열. 행/열 구분 없음 |
| `np.array([[1,2,3]])` | `(1,3)` | 1행 3열 행렬 (행벡터) |
| `np.array([[1],[2],[3]])` | `(3,1)` | 3행 1열 행렬 (열벡터) |
| `np.array([1,2,3]).T` | `(3,)` | **변화 없음** — 1D는 전치가 무의미 |

**(2)**

| 연산 | 결과 | 이유 |
|---|---|---|
| `v @ v` | 14 (스칼라) | 1D끼리 `@`는 내적 |
| `v.reshape(-1,1) @ v.reshape(1,-1)` | shape `(3,3)` | $(3,1)\cdot(1,3)$ = 외적 |
| `v.reshape(1,-1) @ v.reshape(-1,1)` | shape `(1,1)` | $(1,3)\cdot(3,1)$ = 내적(행렬 형태) |

**(3)** 편향 트릭:

$$\mathbf{x}' = \begin{bmatrix} 84 \\ 10 \\ 1 \end{bmatrix}, \quad \mathbf{w}' = \begin{bmatrix} 300 \\ -200 \\ 5000 \end{bmatrix}$$

$$\hat{y} = 300\times84 + (-200)\times10 + 5000\times1 = 28200$$

In [4]:
v = np.array([1, 2, 3])
print("v @ v                          =", v @ v)                                    # 14
print("v.reshape(-1,1) @ v.reshape(1,-1) shape:",
      (v.reshape(-1,1) @ v.reshape(1,-1)).shape)   # (3,3)
print("v.reshape(1,-1) @ v.reshape(-1,1) shape:",
      (v.reshape(1,-1) @ v.reshape(-1,1)).shape)   # (1,1)

x_aug = np.array([[84], [10], [1]])
w_aug = np.array([[300], [-200], [5000]])
print("Prediction:", (x_aug.T @ w_aug)[0,0])   # 28200

v @ v                          = 14
v.reshape(-1,1) @ v.reshape(1,-1) shape: (3, 3)
v.reshape(1,-1) @ v.reshape(-1,1) shape: (1, 1)
Prediction: 28200


## 문제 4. 인덱싱

| 식 | 결과 |
|---|---|
| `X[2, 1]` | 80 |
| `X[-1]` | `[11 22 33]` |
| `X[1:3, 1:]` | `[[50 60][80 90]]` |
| `X[X > 50]` | `[60 70 80 90]` |
| `X[[0, 3]]` | `[[10 20 30][11 22 33]]` |
| `X[:, [2, 0]]` | `[[30 10][60 40][90 70][33 11]]` |

In [5]:
X = np.array([[10,20,30],[40,50,60],[70,80,90],[11,22,33]])
print(X[2, 1])          # 80
print(X[-1])            # [11 22 33]
print(X[1:3, 1:])       # [[50 60][80 90]]
print(X[X > 50])        # [60 70 80 90]
print(X[[0, 3]])        # [[10 20 30][11 22 33]]
print(X[:, [2, 0]])     # [[30 10][60 40][90 70][33 11]]

80
[11 22 33]
[[50 60]
 [80 90]]
[60 70 80 90]
[[10 20 30]
 [11 22 33]]
[[30 10]
 [60 40]
 [90 70]
 [33 11]]


---
# Part C.  Lab 1 버그 잡기 정답

## 버그 1. shape `(1,2)` vs `(2,1)`

**원인:** `w = np.array([[300, -200]])` → shape `(1,2)`.  
`X @ w`는 $(3,2)\cdot(1,2)$ → 앞 열(2) ≠ 뒤 행(1) → 오류.

**수정:** `w`를 shape `(2,1)` 열벡터로 만들어야 $(3,2)\cdot(2,1)=(3,1)$.

In [6]:
X = np.array([[84,10],[59,5],[112,20]])

w_wrong = np.array([[300, -200]])        # (1,2) ← wrong
w_fixed = np.array([[300], [-200]])      # (2,1) ← correct

print("Wrong w shape:", w_wrong.shape)
print("Fixed w shape:", w_fixed.shape)
print("y_hat:\n", X @ w_fixed)           # (3,1)

Wrong w shape: (1, 2)
Fixed w shape: (2, 1)
y_hat:
 [[23200]
 [16700]
 [29600]]


## 버그 2. `and` vs `&`

**원인:** Python의 `and`는 두 스칼라 값의 논리 연산. 배열에 쓰면 `ValueError: ambiguous truth value`.  
NumPy 배열의 원소별 논리 연산은 `&` (and), `|` (or), `~` (not) 을 사용해야 함.


In [7]:
X = np.array([[84.,10.],[59.,5.],[112.,20.],[76.,15.]])

# Wrong: Python 'and' on arrays
try:
    mask_wrong = X[:, 0] > 30 and X[:, 1] < 15
except ValueError as e:
    print("Error:", e)

# Fixed: element-wise '&'
mask_fixed = (X[:, 0] > 30) & (X[:, 1] < 15)
print("mask:", mask_fixed)
print("result:\n", X[mask_fixed])   # [[84. 10.] [59. 5.] [76. 15.]]

Error: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
mask: [ True  True False False]
result:
 [[84. 10.]
 [59.  5.]]


## 버그 3. `axis=1` vs `axis=0`

**원인:** `axis=1`은 각 행의 평균/표준편차 → shape `(3,)` (샘플별).  
특성별 정규화는 각 열의 통계량이 필요하므로 `axis=0` → shape `(2,)` (특성별).

**함정:** 에러 없이 실행되지만 결과가 틀림 → 가장 위험한 종류.

In [8]:
X = np.array([[84.,10.],[59.,5.],[112.,20.]])

# Wrong (axis=1): row-wise stats
mean_wrong = X.mean(axis=1)   # shape (3,)
X_bad = (X - mean_wrong.reshape(-1,1)) / X.std(axis=1).reshape(-1,1)
print("Wrong column means:", X_bad.mean(axis=0).round(3))   # not ~0

# Fixed (axis=0): column-wise stats
mean = X.mean(axis=0)   # shape (2,)
std  = X.std(axis=0)
X_norm = (X - mean) / std   # broadcasting: (3,2) - (2,) → (3,2)
print("Fixed column means (≈ 0):", X_norm.mean(axis=0).round(10))
print("Fixed column stds  (≈ 1):", X_norm.std(axis=0).round(10))

Wrong column means: [ 1. -1.]
Fixed column means (≈ 0): [0. 0.]
Fixed column stds  (≈ 1): [1. 1.]


---
# Part D.  Lab 1 코딩 실습 정답

In [9]:
# Lab 1
a = np.array([2, -1, 3])
b = np.array([4,  2, -1])
print(a + b)                 # [6  1  2]
print(2*a - b)               # [0 -4  7]
print(np.dot(a, b))          # 3
print(np.linalg.norm(a))     # 3.7416...

[6 1 2]
[ 0 -4  7]
3
3.7416573867739413


In [10]:
# Lab 2
X = np.array([[10,20,30],[40,50,60],[70,80,90],[11,22,33]])
print(X[2, 1])          # 80
print(X[-1])            # [11 22 33]
print(X[1:3, 1:])       # [[50 60][80 90]]
print(X[X > 50])        # [60 70 80 90]
print(X[[0, 3]])        # [[10 20 30][11 22 33]]
print(X[:, [2, 0]])     # [[30 10]...]

80
[11 22 33]
[[50 60]
 [80 90]]
[60 70 80 90]
[[10 20 30]
 [11 22 33]]
[[30 10]
 [60 40]
 [90 70]
 [33 11]]


In [11]:
# Lab 3
X_raw = np.array([[84.,10.],[59.,5.],[112.,20.]])

mean   = X_raw.mean(axis=0)
std    = X_raw.std(axis=0)
X_norm = (X_raw - mean) / std
print("Normalized:\n", X_norm.round(3))

ones  = np.ones((3, 1))
X_aug = np.hstack([X_norm, ones])   # shape (3,3)
print("Augmented shape:", X_aug.shape)

w     = np.array([[1.0], [-0.5], [0.0]])
y_hat = X_aug @ w
print("Predictions:\n", y_hat.round(3))

Normalized:
 [[-0.046 -0.267]
 [-1.201 -1.069]
 [ 1.247  1.336]]
Augmented shape: (3, 3)
Predictions:
 [[ 0.087]
 [-0.666]
 [ 0.579]]
